server:
  port: 8081

eureka:
  instance:
    hostname: eureka-server-discovery.onrender.com
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_HOST:https://eureka-server-discovery.onrender.com/eureka/}
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false